spring:
  data:
    mongodb:
      username: pius
      password: 6eight14
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.pius.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.pius.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: pius
    password: pius
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040